Django Colors/djangocolor/colormean/urls.py
from django.urls import path
from . import views

app_name = "colormean"

urlpatterns = [
    path('',views.primarycolor,name='primarycolor'),
    path('secondarycolor/',views.secondarycolor,name='secondarycolor'),
    path('specialcolor/',views.specialcolor,name='specialcolor')
]

Django Colors/djangocolor/djangocolor/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('colormean/',include('colormean.urls'))
]

Django Colors/djangocolor/colormean/models.py
from django.db import models

# Create your models here.

Django Colors/djangocolor/colormean/views.py
from django.shortcuts import render

# Create your views here.

def primarycolor(request):
    return render(request,'colormean/primarycolor.html')

def secondarycolor(request):
    return render(request,'colormean/secondarycolor.html')

def specialcolor(request):
    return render(request,'colormean/specialcolor.html')

Django Colors/djangocolor/colormean/templates/colormean/primarycolor.html
{% extends "base.html" %}

{% block content %}

<br><br><br><br>

<h1>Ana Renkler</h1>

<br>

<div class="card" style="width: 75rem; border-color: blue;">
  <div class="card-body">
    <h5 class="card-title" style="color: blue;">Mavi</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ana Renk</h6>
  <ol>
    <p class="card-text">Mavi rengi, genellikle sakinlik, dinginlik ve huzur ile özdeşleştirilir. Bununla birlikte, mavi aynı zamanda güvenilirlik, sadakat ve bilgeliği temsil eder. İş dünyasında, mavi sıklıkla profesyonellik, resmiyet ve güvenirlik ile bağdaştırılır. Bu nedenle birçok kurum, logosunda veya kurumsal renklerinde maviyi tercih eder.</p>
    <p class="card-text">Mavi, özellikle açık tonlarıyla, insan psikolojisi üzerinde sakinleştirici bir etkiye sahiptir. Stresli ve gergin zamanlarda mavi tonlarına maruz kalmak, insanın kendini daha rahat ve huzurlu hissetmesine yardımcı olabilir.</p>
    <p class="card-text">Bazı araştırmalar, mavi rengin, insanların dikkatini toplamalarına ve daha iyi odaklanmalarına yardımcı olabileceğini göstermektedir</p>
    <p class="card-text">Mavi, özellikle yatak odaları ve çalışma alanları için idealdir. Huzurlu atmosferiyle rahat bir uyku sağlarken, odaklanma ve konsantrasyonu artırarak çalışma verimliliğini de destekler.</p>
  </ol>
  </div>
</div>

<br>

<div class="card" style="width: 75rem; border-color: red">
  <div class="card-body">
    <h5 class="card-title" style="color: red">Kırmızı</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ana Renk</h6>
  <ol>
    <p class="card-text">Kırmızı rengin anlamı tutku, aşk, güç, enerji, sıcaklık, hareketlilik ve heyecandır. Kırmızı rengi, yüksek enerji seviyesi ile ilişkilendiririz ve birçok kültürde şans, mutluluk ve zenginlik ile ilişkilendirilir. Kırmızı renk, doğada da bol miktarda bulunur ve birçok canlıda görülür.</p>
    <p class="card-text">Kırmızı renk anlamı, tarih boyunca değişmemiş ve birçok kültürde benzer şekilde yorumlanmıştır. Kırmızı renk, antik Mısır'da kraliyet ve tanrıların rengi olarak kabul edilirdi. Çin kültüründe, kırmızı renk, şans, mutluluk ve zenginliğin sembolüdür. Hindistan'da, kırmızı renk, düğünlerde ve diğer kutlamalarda kullanılan geleneksel bir renktir ve aşkın sembolüdür.</p>
    <p class="card-text">Kırmızı renk genel olarak insanlar üzerinde uyarıcı ve dikkat çekici bir etkiye sahiptir. Bu sebepten, kırmızı renk özellikle uyarı işaretlerinde sıklıkla kullanılır. Trafik işaretlerinden tutun, internet sitesi tasarımlarına kadar pek çok alanda yasaklı ya da tehlikeli bir şeyi ifade ederken genellikle kırmızı renk kullanılır. Kırmızı rengin bu dikkat çekici özelliği, pazarlama alanında kullanılmasının da önünü açar. Reklamlarda, afişlerde, pazarlama görsellerinde ve benzeri pazarlama materyallerinde en çok kullanılan renklerden biri de kırmızı rengidir.</p>
  </ol>
  </div>
</div>

<br>

<div class="card" style="width: 75rem; border-color: yellow">
  <div class="card-body">
    <h5 class="card-title" style="color:yellow">Sarı</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ana Renk</h6>
  <ol>
    <p class="card-text">Sarı renk, doğada sıkça rastlanan ve göz alıcı bir renktir. Güneş, çiçekler, meyveler ve sonbahar yaprakları, sarının doğal dünyadaki çeşitli temsilleridir. Ancak sarı rengin anlamı, kültürel ve bireysel bağlamda farklılık gösterebilir. Psikoloji, sanat ve tasarım alanında sarı renk özel bir yer tutar ve bireyler üzerinde farklı etkiler yaratabilir.</p>
    <p class="card-text">Sarı renk sıklıkla enerji ve neşe ile ilişkilendirilir. Aydınlık ve canlı tonları, bireylerin enerji seviyelerini yükseltmeye yardımcı olabilir. Ayrıca sarı, sıcaklık ve aydınlanma hissi uyandıran bir renktir, bu nedenle insanlar üzerinde pozitif bir etki yaratabilir.</p>
    <p class="card-text">Sarı, aynı zamanda optimizm ve umut rengi olarak da kabul edilir. Daha parlak ve mutlu bir geleceği temsil eder ve bireylerde olumlu düşünceler uyandırabilir.</p>
    <p class="card-text">Her ne kadar sarı renk pozitif duygularla ilişkilendirilse de, aşırıya kaçıldığında stres ve rahatsızlık hissine neden olabilir. Ayrıca sarı, kıskançlık ve ihanet gibi olumsuz duyguları da simgeler.</p>
  </ol>
  </div>
</div>

<br>

{% endblock %}

Django Colors/djangocolor/colormean/templates/colormean/secondarycolor.html
{% extends "base.html" %}

{% block content %}

<br><br><br><br>

<h1>Ara Renkler</h1>

<br>

<div class="card" style="width: 75rem; border-color: green;">
    <div class="card-body">
      <h5 class="card-title" style="color: green;">Yeşil</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Ara Renk</h6>
    <ol>
      <p class="card-text">Yeşil, doğanın rengi olarak bilinir ve bolluk, ferahlık ve yeniden doğuşu simgeler. Ayrıca, huzur, dinginlik ve rahatlama ile de ilişkilendirilir. Psikolojik açıdan yeşil renk, insan üzerinde dengeleyici ve yenileyici bir etki yaratır.</p>
      <p class="card-text">Yeşil renk, doğal bir denge ve huzur hissi uyandırır. İnsan psikolojisi üzerinde rahatlatıcı bir etkiye sahiptir ve stresi azaltmaya yardımcı olabilir.</p>
      <p class="card-text">Yeşil, doğanın ve yeniden doğuşun rengidir. Yepyeni başlangıçları ve tazelik hissini simgeler.</p>
      <p class="card-text">Yeşil, verimliliği ve büyümeyi temsil eder. İnsanların odaklanmasını ve dikkatini artırmalarına yardımcı olarak, daha verimli olmalarını sağlar</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: purple;">
    <div class="card-body">
      <h5 class="card-title" style="color: purple;">Mor</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Ara Renk</h6>
    <ol>
      <p class="card-text"> Mor, geleneksel olarak lüks ve zenginlikle ilişkilendirilir. Bu nedenle, mor renk, pahalı ürünlerin ve markaların logosunda ve ambalajında sıkça tercih edilir.</p>
      <p class="card-text">Mor, gizem, mistisizm ve spiritüalizmle ilişkilendirilir. Bu renk, mistik deneyimleri, içsel düşünceyi ve ruhsal farkındalığı sembolize edebilir.</p>
      <p class="card-text"> Mor, liderlik özellikleri ve yetenekleri temsil edebilir. Bu nedenle, mor, liderlerin veya karar vericilerin gücünü yansıtmak için kullanılabilir.</p>
      <p class="card-text">Mor, zıt duygusal uçlar arasında bir denge sağlayabilir. Bu renk, sakinleştirici ve dengeleyici bir etki yaratabilir, bu da insanları duygusal olarak dengelemeye yardımcı olabilir.</p>
    </ol>  
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: orange;">
    <div class="card-body">
      <h5 class="card-title" style="color: orange;">Turuncu</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Ara Renk</h6>
    <ol>
      <p class="card-text">Turuncu rengi psikoloji biliminde canlılığı, heyecanı ve umudu temsil eder. Kararlılık, azim ve iyimserlik, turuncu rengiyle özdeşleşmiş olan kişilerin ortak özellikleri arasında yer alır.</p>
      <p class="card-text">Turuncu, yaşanan tüm olumsuzluklara rağmen asla yılgınlığa kapılmamanın ve hedefleri gerçekleştirmek için aynı kararlılık ile mücadele etmenin sembolüdür. Bu renk aynı zamanda cesaret anlamına gelir.</p>
      <p class="card-text">Turuncu renginin, iştah açıcı ve enerji verici bir etkisi vardır. Bu nedenle, restoranlar ve yiyecek ile ilgili diğer işletmelerde sıklıkla kullanılır.</p>
      <p class="card-text">Turuncu, aynı zamanda iyimserliği ve umudu simgeler. Bireylere daha açık fikirli ve olumlu düşünme kapasitesi katabilir</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: pink;">
    <div class="card-body">
      <h5 class="card-title" style="color: pink;">Pembe</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Ara Renk</h6>
    <ol>
      <p class="card-text">Pembe renk, sıklıkla kadınsılık, romantizm ve masumiyet ile ilişkilendirilir. Ancak pembe, sadece bu kavramlarla sınırlı değildir. Pembenin psikolojik etkileri, tonuna ve kullanıldığı bağlama göre değişiklik gösterebilir.</p>
      <p class="card-text">Pembe, özellikle pastel tonlarıyla, sakinleştirici bir etkiye sahiptir. Bu nedenle bazı cezaevleri ve akıl hastanelerinde huzursuzluk yaratmamak adına pembe tonları kullanılır.</p>
      <p class="card-text">Canlı ve parlak pembe tonları, enerji ve coşku verici etkiye sahiptir. Bu nedenle spor giyimde veya enerji vermek istenen alanlarda bu tonlar tercih edilebilir.</p>
      <p class="card-text">Pembe, özellikle yatak odaları ve çocuk odaları için uygun bir renktir. Huzurlu ve sakin bir atmosfer yaratırken, aynı zamanda odaya sıcaklık katar.</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: turquoise;">
  <div class="card-body">
    <h5 class="card-title" style="color: turquoise;">Turkuaz</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ara Renk</h6>
    <p class="card-text">Turkuaz, mavi ile yeşilin birleşiminden oluşan, denizin derinliklerini ve tropik suları anımsatan bir renktir. Hem doğal bir sakinlik duygusu hem de canlandırıcı bir enerjiye sahip olan turkuazın anlamı ve psikolojik etkileri oldukça zengindir.</p>
    <p class="card-text">Turkuaz, mavi ve yeşilin özelliklerini birleştirerek denge ve uyumu temsil eder. Bu, hem doğal bir huzur ve sakinlik duygusu, hem de canlanma ve yeniden enerji bulma anlamına gelir.</p>
    <p class="card-text">Turkuaz, özgün düşünceleri ve yaratıcı enerjiyi teşvik eder.Turkuaz, özgün düşünceleri ve yaratıcı enerjiyi teşvik eder.Turkuaz, duygusal dengesizlikleri dengelemeye yardımcı olabilir</p>
    <p class="card-text">Turkuaz, özellikle banyo, yatak odası veya çalışma alanları için uygundur. Sakin atmosferiyle rahat bir uyku veya çalışma ortamı sağlarken, yaratıcılığı teşvik eden tonlarıyla da daha üretken olmanıza yardımcı olabilir.</p>
  </div>
</div>

<br>
  

{% endblock %}

Django Colors/djangocolor/colormean/templates/colormean/specialcolor.html
{% extends "base.html" %}

{% block content %}

<br><br><br><br>

<h1>Özel Renkler</h1>

<br>

<div class="card" style="width: 75rem;">
    <div class="card-body">
      <h5 class="card-title">Beyaz</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Özel Renk</h6>
    <ol>
      <p class="card-text">Beyaz renk, doğada ve insan yapımı nesnelerde sıkça karşımıza çıkan, saf ve temiz bir enerjiye sahip olan bir renktir. Tarihsel ve kültürel bağlamlarda birçok anlam taşıyan beyaz, psikolojik olarak da insanlar üzerinde belirgin etkilere sahiptir.</p>
      <p class="card-text">Beyaz, genellikle saflık, masumiyet, berraklık ve başlangıçla ilişkilendirilir.Düğünlerde beyaz gelinlikler, yeni doğmuş bebekler için beyaz giysiler; masumiyetin, saflığın ve yeni bir başlangıcın bir sembolü olarak kabul edilir</p>
      <p class="card-text">Beyaz bayrak, evrensel bir barış ve teslimiyet sembolüdür.Beyaz, berrak bir zihni ve boş bir sayfayı temsil eder.</p>
      <p class="card-text">Beyaz, bir alanda daha geniş ve açık bir his yaratır. Özellikle küçük mekanlarda beyaz renk kullanımı, mekanın daha büyük ve geniş görünmesine yardımcı olur.</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem;">
    <div class="card-body">
      <h5 class="card-title">Siyah</h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">Özel Renk</h6>
    <ol>
      <p class="card-text">Siyah, renk paletinde ayrı bir yere sahip olan ve birçok kültürde derin anlamlar taşıyan bir renktir. Hem modada hem de sanatta sıkça tercih edilen siyah, duyguları ve psikolojik durumları büyük ölçüde etkileyebilir</p>
      <p class="card-text">Siyah genellikle güç, otorite, ölüm, zarafet ve gizemle ilişkilendirilir. Bazı kültürlerde yas ve üzüntüyü simgelerken, bazılarında asaleti ve prestiji temsil eder.</p>
      <p class="card-text">Siyah sıklıkla otoriteyi ve resmiyeti temsil eder. İş dünyasında siyah takım elbiseler ve kıyafetler, profesyonellik ve ciddiyetin bir göstergesi olarak kabul edilir.</p>
      <p class="card-text">Birçok kültürde siyah, ölümü ve yası simgeler. Bu, cenaze törenlerinde siyah giysilerin tercih edilmesinin ana nedenlerinden biridir.Moda dünyasında siyah, zarafetin ve sofistikenin rengidir. "Küçük siyah elbise" kavramı bu anlamda ikonikleşmiştir.</p>
    </ol>
    </div>
  </div>

<br>  

{% endblock %}

Django Colors/djangocolor/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Color Mean</title>

</head>
<body>
    
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'colormean:primarycolor' %}">Color Mean</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'colormean:primarycolor' %}">Ana Renkler</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'colormean:secondarycolor' %}">Ara Renkler</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'colormean:specialcolor' %}">Özel Renkler</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock %}

</body>
</html>